// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelAppointmentData, CancelAppointmentErrors, CancelAppointmentResponses, CreateAppointmentData, CreateAppointmentErrors, CreateAppointmentResponses, GetAppointmentByIdData, GetAppointmentByIdErrors, GetAppointmentByIdResponses, GetAvailableSpecialistsData, GetAvailableSpecialistsErrors, GetAvailableSpecialistsResponses, GetDocsData, GetDocsResponses, GetPastAppointmentsData, GetPastAppointmentsErrors, GetPastAppointmentsResponses, GetScalarJsData, GetScalarJsResponses, GetSpecialistBookingDataData, GetSpecialistBookingDataErrors, GetSpecialistBookingDataResponses, GetUpcomingAppointmentsData, GetUpcomingAppointmentsErrors, GetUpcomingAppointmentsResponses, GetUserAppointmentsData, GetUserAppointmentsErrors, GetUserAppointmentsResponses, HealthData, HealthResponses, LinksData, LinksResponses, ProvisionUserData, ProvisionUserErrors, ProvisionUserResponses, UpdateAppointmentData, UpdateAppointmentErrors, UpdateAppointmentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Cancel appointment
 *
 * Cancels an existing appointment
 */
export const cancelAppointment = <ThrowOnError extends boolean = false>(options: Options<CancelAppointmentData, ThrowOnError>) => {
    return (options.client ?? client).delete<CancelAppointmentResponses, CancelAppointmentErrors, ThrowOnError>({
        url: '/api/v1/appointments/{id}',
        ...options
    });
};

/**
 * Get appointment by ID
 *
 * Returns a specific appointment by its unique identifier
 */
export const getAppointmentById = <ThrowOnError extends boolean = false>(options: Options<GetAppointmentByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAppointmentByIdResponses, GetAppointmentByIdErrors, ThrowOnError>({
        url: '/api/v1/appointments/{id}',
        ...options
    });
};

/**
 * Update appointment
 *
 * Updates an existing appointment
 */
export const updateAppointment = <ThrowOnError extends boolean = false>(options: Options<UpdateAppointmentData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateAppointmentResponses, UpdateAppointmentErrors, ThrowOnError>({
        url: '/api/v1/appointments/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Provision a user
 *
 * Creates a new Domain User. This action is triggered by the authentication service when a user is created.
 *
 */
export const provisionUser = <ThrowOnError extends boolean = false>(options: Options<ProvisionUserData, ThrowOnError>) => {
    return (options.client ?? client).post<ProvisionUserResponses, ProvisionUserErrors, ThrowOnError>({
        url: '/api/v1/user-provisions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get user appointments
 *
 * Returns all appointments for the authenticated user
 */
export const getUserAppointments = <ThrowOnError extends boolean = false>(options?: Options<GetUserAppointmentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserAppointmentsResponses, GetUserAppointmentsErrors, ThrowOnError>({
        url: '/api/v1/appointments',
        ...options
    });
};

/**
 * Create appointment
 *
 * Creates a new appointment with a specialist
 */
export const createAppointment = <ThrowOnError extends boolean = false>(options: Options<CreateAppointmentData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateAppointmentResponses, CreateAppointmentErrors, ThrowOnError>({
        url: '/api/v1/appointments',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getDocs = <ThrowOnError extends boolean = false>(options?: Options<GetDocsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDocsResponses, unknown, ThrowOnError>({
        url: '/docs',
        ...options
    });
};

export const getScalarJs = <ThrowOnError extends boolean = false>(options?: Options<GetScalarJsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetScalarJsResponses, unknown, ThrowOnError>({
        url: '/docs/scalar.js',
        ...options
    });
};

/**
 * Get available specialists
 *
 * Returns list of all active specialists
 */
export const getAvailableSpecialists = <ThrowOnError extends boolean = false>(options?: Options<GetAvailableSpecialistsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAvailableSpecialistsResponses, GetAvailableSpecialistsErrors, ThrowOnError>({
        url: '/api/v1/specialists',
        ...options
    });
};

/**
 * Get specialist booking data
 *
 * Returns available time slots for a specialist within a date range
 */
export const getSpecialistBookingData = <ThrowOnError extends boolean = false>(options: Options<GetSpecialistBookingDataData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSpecialistBookingDataResponses, GetSpecialistBookingDataErrors, ThrowOnError>({
        url: '/api/v1/specialists/specialists/{specialistId}/booking-data',
        ...options
    });
};

/**
 * Get upcoming appointments
 *
 * Returns upcoming appointments for the authenticated user
 */
export const getUpcomingAppointments = <ThrowOnError extends boolean = false>(options?: Options<GetUpcomingAppointmentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUpcomingAppointmentsResponses, GetUpcomingAppointmentsErrors, ThrowOnError>({
        url: '/api/v1/appointments/upcoming',
        ...options
    });
};

/**
 * Get past appointments
 *
 * Returns past appointments for the authenticated user
 */
export const getPastAppointments = <ThrowOnError extends boolean = false>(options?: Options<GetPastAppointmentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPastAppointmentsResponses, GetPastAppointmentsErrors, ThrowOnError>({
        url: '/api/v1/appointments/history',
        ...options
    });
};

/**
 * Actuator root web endpoint
 */
export const links = <ThrowOnError extends boolean = false>(options?: Options<LinksData, ThrowOnError>) => {
    return (options?.client ?? client).get<LinksResponses, unknown, ThrowOnError>({
        url: '/actuator',
        ...options
    });
};

/**
 * Actuator web endpoint 'health'
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
        url: '/actuator/health',
        ...options
    });
};
