// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

/**
 * Appointment status
 */
export type AppointmentStatus = 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';

/**
 * Request to update an appointment
 */
export type UpdateAppointmentRequest = {
    /**
     * New appointment date and time (must be in the future)
     */
    appointment_date?: string;
    status?: AppointmentStatus;
    /**
     * Additional notes
     */
    notes?: string;
    /**
     * Cancellation reason (required if status is CANCELLED)
     */
    cancellation_reason?: string;
};

/**
 * Appointment details
 */
export type AppointmentResponse = {
    /**
     * Appointment unique identifier
     */
    id: string;
    client: ClientSummary;
    specialist: SpecialistSummary;
    /**
     * Appointment date and time
     */
    appointment_date: string;
    /**
     * Duration in minutes
     */
    duration_minutes: number;
    status: AppointmentStatus;
    /**
     * Additional notes
     */
    notes?: string;
    /**
     * Cancellation reason if cancelled
     */
    cancellation_reason?: string;
    /**
     * Creation timestamp
     */
    created_at: string;
    /**
     * Last update timestamp
     */
    updated_at: string;
};

/**
 * Summary of client information
 */
export type ClientSummary = {
    /**
     * Client unique identifier
     */
    id: string;
    /**
     * Client full name
     */
    name: string;
    /**
     * Client email
     */
    email: string;
};

/**
 * Summary of specialist information
 */
export type SpecialistSummary = {
    /**
     * Specialist unique identifier
     */
    id: string;
    /**
     * Specialist full name
     */
    name: string;
    /**
     * Specialty
     */
    specialty: string;
};

/**
 * Validation error response
 */
export type ValidationErrorResponse = {
    timestamp?: string;
    status?: number;
    error?: string;
    messages?: {
        [key: string]: string;
    };
    path?: string;
};

/**
 * API error response
 */
export type ApiErrorResponse = {
    timestamp?: string;
    status?: number;
    error?: string;
    message?: string;
    path?: string;
};

/**
 * Request to provision a user
 */
export type ProvisionUserRequest = {
    /**
     * User ID
     */
    user_id: string;
    /**
     * User email
     */
    email: string;
};

/**
 * Request to create a new appointment
 */
export type CreateAppointmentRequest = {
    /**
     * Specialist unique identifier
     */
    specialist_id: string;
    /**
     * Appointment date and time (must be in the future)
     */
    appointment_date: string;
    /**
     * Additional notes for the appointment
     */
    notes?: string;
};

/**
 * Specialist information
 */
export type SpecialistResponse = {
    /**
     * Specialist unique identifier
     */
    id: string;
    /**
     * Specialist full name
     */
    name: string;
    /**
     * Specialist type name
     */
    specialty: string;
    /**
     * Specialist type ID
     */
    specialty_id: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Whether the specialist is accepting new patients
     */
    is_active: boolean;
    /**
     * Default consultation duration in minutes
     */
    consultation_duration_minutes: number;
};

/**
 * Schedule for a specific day
 */
export type DayScheduleResponse = {
    /**
     * Date for this schedule
     */
    date: string;
    /**
     * List of time slots for this day
     */
    timeslots: Array<TimeSlot>;
};

/**
 * Time slot information
 */
export type TimeSlot = {
    /**
     * Time in HH:mm format
     */
    time: string;
    /**
     * Availability status
     */
    status: 'available' | 'booked';
    /**
     * Appointment ID if booked
     */
    appointment_id?: string;
};

export type Link = {
    href?: string;
    templated?: boolean;
};

export type CancelAppointmentData = {
    body?: never;
    path: {
        /**
         * Appointment unique identifier
         */
        id: string;
    };
    query: {
        /**
         * Cancellation reason
         */
        reason: string;
    };
    url: '/api/v1/appointments/{id}';
};

export type CancelAppointmentErrors = {
    /**
     * Invalid request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden - not your appointment
     */
    403: ApiErrorResponse;
    /**
     * Appointment not found
     */
    404: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type CancelAppointmentError = CancelAppointmentErrors[keyof CancelAppointmentErrors];

export type CancelAppointmentResponses = {
    /**
     * Appointment cancelled successfully
     */
    204: void;
};

export type CancelAppointmentResponse = CancelAppointmentResponses[keyof CancelAppointmentResponses];

export type GetAppointmentByIdData = {
    body?: never;
    path: {
        /**
         * Appointment unique identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{id}';
};

export type GetAppointmentByIdErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden - not your appointment
     */
    403: ApiErrorResponse;
    /**
     * Appointment not found
     */
    404: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetAppointmentByIdError = GetAppointmentByIdErrors[keyof GetAppointmentByIdErrors];

export type GetAppointmentByIdResponses = {
    /**
     * Appointment details
     */
    200: AppointmentResponse;
};

export type GetAppointmentByIdResponse = GetAppointmentByIdResponses[keyof GetAppointmentByIdResponses];

export type UpdateAppointmentData = {
    body: UpdateAppointmentRequest;
    path: {
        /**
         * Appointment unique identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{id}';
};

export type UpdateAppointmentErrors = {
    /**
     * Invalid request
     */
    400: ValidationErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden - not your appointment
     */
    403: ApiErrorResponse;
    /**
     * Appointment not found
     */
    404: ApiErrorResponse;
    /**
     * New time slot already booked
     */
    409: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type UpdateAppointmentError = UpdateAppointmentErrors[keyof UpdateAppointmentErrors];

export type UpdateAppointmentResponses = {
    /**
     * Appointment updated successfully
     */
    200: AppointmentResponse;
};

export type UpdateAppointmentResponse = UpdateAppointmentResponses[keyof UpdateAppointmentResponses];

export type ProvisionUserData = {
    body: ProvisionUserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user-provisions';
};

export type ProvisionUserErrors = {
    /**
     * Invalid request
     */
    400: ValidationErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Forbidden
     */
    403: ApiErrorResponse;
};

export type ProvisionUserError = ProvisionUserErrors[keyof ProvisionUserErrors];

export type ProvisionUserResponses = {
    /**
     * User provisioned successfully
     */
    201: unknown;
};

export type GetUserAppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type GetUserAppointmentsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetUserAppointmentsError = GetUserAppointmentsErrors[keyof GetUserAppointmentsErrors];

export type GetUserAppointmentsResponses = {
    /**
     * List of user appointments
     */
    200: Array<AppointmentResponse>;
};

export type GetUserAppointmentsResponse = GetUserAppointmentsResponses[keyof GetUserAppointmentsResponses];

export type CreateAppointmentData = {
    body: CreateAppointmentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type CreateAppointmentErrors = {
    /**
     * Invalid request
     */
    400: ValidationErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Specialist not found
     */
    404: ApiErrorResponse;
    /**
     * Time slot already booked
     */
    409: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type CreateAppointmentError = CreateAppointmentErrors[keyof CreateAppointmentErrors];

export type CreateAppointmentResponses = {
    /**
     * Appointment created successfully
     */
    201: AppointmentResponse;
};

export type CreateAppointmentResponse = CreateAppointmentResponses[keyof CreateAppointmentResponses];

export type GetDocsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs';
};

export type GetDocsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDocsResponse = GetDocsResponses[keyof GetDocsResponses];

export type GetScalarJsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs/scalar.js';
};

export type GetScalarJsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetScalarJsResponse = GetScalarJsResponses[keyof GetScalarJsResponses];

export type GetAvailableSpecialistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/specialists';
};

export type GetAvailableSpecialistsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetAvailableSpecialistsError = GetAvailableSpecialistsErrors[keyof GetAvailableSpecialistsErrors];

export type GetAvailableSpecialistsResponses = {
    /**
     * List of specialists
     */
    200: Array<SpecialistResponse>;
};

export type GetAvailableSpecialistsResponse = GetAvailableSpecialistsResponses[keyof GetAvailableSpecialistsResponses];

export type GetSpecialistBookingDataData = {
    body?: never;
    path: {
        /**
         * Specialist unique identifier
         */
        specialistId: string;
    };
    query: {
        /**
         * Start date (ISO-8601 format)
         */
        startDate: string;
        /**
         * End date (ISO-8601 format)
         */
        endDate: string;
    };
    url: '/api/v1/specialists/specialists/{specialistId}/booking-data';
};

export type GetSpecialistBookingDataErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Specialist not found
     */
    404: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetSpecialistBookingDataError = GetSpecialistBookingDataErrors[keyof GetSpecialistBookingDataErrors];

export type GetSpecialistBookingDataResponses = {
    /**
     * Specialist booking schedule
     */
    200: Array<DayScheduleResponse>;
};

export type GetSpecialistBookingDataResponse = GetSpecialistBookingDataResponses[keyof GetSpecialistBookingDataResponses];

export type GetUpcomingAppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/upcoming';
};

export type GetUpcomingAppointmentsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetUpcomingAppointmentsError = GetUpcomingAppointmentsErrors[keyof GetUpcomingAppointmentsErrors];

export type GetUpcomingAppointmentsResponses = {
    /**
     * List of upcoming appointments
     */
    200: Array<AppointmentResponse>;
};

export type GetUpcomingAppointmentsResponse = GetUpcomingAppointmentsResponses[keyof GetUpcomingAppointmentsResponses];

export type GetPastAppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/history';
};

export type GetPastAppointmentsErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Internal server error
     */
    500: ApiErrorResponse;
};

export type GetPastAppointmentsError = GetPastAppointmentsErrors[keyof GetPastAppointmentsErrors];

export type GetPastAppointmentsResponses = {
    /**
     * List of past appointments
     */
    200: Array<AppointmentResponse>;
};

export type GetPastAppointmentsResponse = GetPastAppointmentsResponses[keyof GetPastAppointmentsResponses];

export type LinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator';
};

export type LinksResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: {
            [key: string]: Link;
        };
    };
};

export type LinksResponse = LinksResponses[keyof LinksResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
