// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

/**
 * Appointment status
 */
export type AppointmentStatus = 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';

/**
 * Request to update an appointment
 */
export type UpdateAppointmentRequest = {
    /**
     * New appointment date and time (must be in the future)
     */
    appointment_date?: string;
    status?: AppointmentStatus;
    /**
     * Additional notes
     */
    notes?: string;
    /**
     * Cancellation reason (required if status is CANCELLED)
     */
    cancellation_reason?: string;
};

/**
 * Appointment details
 */
export type AppointmentResponse = {
    /**
     * Appointment unique identifier
     */
    id: string;
    client: ClientSummary;
    specialist: SpecialistSummary;
    /**
     * Appointment date and time
     */
    appointment_date: string;
    /**
     * Duration in minutes
     */
    duration_minutes: number;
    status: AppointmentStatus;
    /**
     * Additional notes
     */
    notes?: string;
    /**
     * Cancellation reason if cancelled
     */
    cancellation_reason?: string;
    /**
     * Creation timestamp
     */
    created_at: string;
    /**
     * Last update timestamp
     */
    updated_at: string;
};

/**
 * Summary of client information
 */
export type ClientSummary = {
    /**
     * Client unique identifier
     */
    id: string;
    /**
     * Client full name
     */
    name: string;
    /**
     * Client email
     */
    email: string;
};

/**
 * Summary of specialist information
 */
export type SpecialistSummary = {
    /**
     * Specialist unique identifier
     */
    id: string;
    /**
     * Specialist full name
     */
    name: string;
    specialty: SpecialistTypeEnum;
};

/**
 * Specialty
 */
export type SpecialistTypeEnum = 'CARDIOLOGY' | 'DERMATOLOGY' | 'GENERAL_PRACTICE' | 'DENTISTRY';

/**
 * RFC 7807 Problem Detail with validation error extensions
 */
export type ValidationProblemDetail = {
    /**
     * A URI reference that identifies the problem type
     */
    type?: string;
    /**
     * A short, human-readable summary of the problem type
     */
    title?: string;
    /**
     * The HTTP status code
     */
    status?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence of the problem
     */
    instance?: string;
    /**
     * List of invalid user IDs that failed validation
     */
    invalid_ids?: Array<string>;
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

/**
 * RFC 7807 Problem Detail for HTTP APIs
 */
export type ApiProblemDetail = {
    /**
     * A URI reference that identifies the problem type
     */
    type?: string;
    /**
     * A short, human-readable summary of the problem type
     */
    title?: string;
    /**
     * The HTTP status code
     */
    status?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence of the problem
     */
    instance?: string;
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

/**
 * Request to provision a user
 */
export type ProvisionUserRequest = {
    /**
     * User ID
     */
    user_id: string;
    /**
     * User email
     */
    email: string;
    /**
     * Primary specialist ID
     */
    specialist_id: string;
};

/**
 * Schema to validate the existing user IDs on the Auth provider to ensure that they are in sync
 */
export type ValidateAuthUserIds = {
    ids?: Array<string>;
};

/**
 * Request to create a new appointment
 */
export type CreateAppointmentRequest = {
    /**
     * Specialist unique identifier
     */
    specialist_id: string;
    /**
     * Appointment date and time (must be in the future)
     */
    appointment_date: string;
    /**
     * Additional notes for the appointment
     */
    notes?: string;
};

/**
 * User medicines response
 */
export type UserMedicinesResponse = {
    medicine_name?: string;
    dosage?: string;
    frequency?: string;
    start_date?: string;
    end_date?: string;
};

/**
 * Specialist information
 */
export type SpecialistResponse = {
    /**
     * Specialist unique identifier
     */
    id: string;
    /**
     * Specialist full name
     */
    name: string;
    specialty: SpecialistTypeEnum;
    /**
     * Email address
     */
    email: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Whether the specialist is accepting new patients
     */
    is_active: boolean;
    /**
     * Default consultation duration in minutes
     */
    consultation_duration_minutes: number;
};

/**
 * Specialist type
 */
export type SpecialistTypeResponse = {
    type?: SpecialistTypeEnum;
};

/**
 * Schedule for a specific day
 */
export type DayScheduleResponse = {
    /**
     * Date for this schedule
     */
    date: string;
    /**
     * List of time slots for this day
     */
    timeslots: Array<TimeSlot>;
};

/**
 * Time slot information
 */
export type TimeSlot = {
    /**
     * Time in HH:mm format
     */
    time: string;
    /**
     * Availability status
     */
    status: 'available' | 'booked';
    /**
     * Appointment ID if booked
     */
    appointment_id?: string;
};

export type Link = {
    href?: string;
    templated?: boolean;
};

export type CancelAppointmentData = {
    body?: never;
    path: {
        /**
         * Appointment unique identifier
         */
        id: string;
    };
    query: {
        /**
         * Cancellation reason
         */
        reason: string;
    };
    url: '/api/v1/appointments/{id}';
};

export type CancelAppointmentErrors = {
    /**
     * Invalid request
     */
    400: ApiProblemDetail;
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Forbidden - not your appointment
     */
    403: ApiProblemDetail;
    /**
     * Appointment not found
     */
    404: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type CancelAppointmentError = CancelAppointmentErrors[keyof CancelAppointmentErrors];

export type CancelAppointmentResponses = {
    /**
     * Appointment cancelled successfully
     */
    204: void;
};

export type CancelAppointmentResponse = CancelAppointmentResponses[keyof CancelAppointmentResponses];

export type GetAppointmentByIdData = {
    body?: never;
    path: {
        /**
         * Appointment unique identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{id}';
};

export type GetAppointmentByIdErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Forbidden - not your appointment
     */
    403: ApiProblemDetail;
    /**
     * Appointment not found
     */
    404: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetAppointmentByIdError = GetAppointmentByIdErrors[keyof GetAppointmentByIdErrors];

export type GetAppointmentByIdResponses = {
    /**
     * Appointment details
     */
    200: AppointmentResponse;
};

export type GetAppointmentByIdResponse = GetAppointmentByIdResponses[keyof GetAppointmentByIdResponses];

export type UpdateAppointmentData = {
    body: UpdateAppointmentRequest;
    path: {
        /**
         * Appointment unique identifier
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{id}';
};

export type UpdateAppointmentErrors = {
    /**
     * Invalid request
     */
    400: ValidationProblemDetail;
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Forbidden - not your appointment
     */
    403: ApiProblemDetail;
    /**
     * Appointment not found
     */
    404: ApiProblemDetail;
    /**
     * New time slot already booked
     */
    409: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type UpdateAppointmentError = UpdateAppointmentErrors[keyof UpdateAppointmentErrors];

export type UpdateAppointmentResponses = {
    /**
     * Appointment updated successfully
     */
    200: AppointmentResponse;
};

export type UpdateAppointmentResponse = UpdateAppointmentResponses[keyof UpdateAppointmentResponses];

export type ProvisionUserData = {
    body: ProvisionUserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user-provisions';
};

export type ProvisionUserErrors = {
    /**
     * Invalid request
     */
    400: ValidationProblemDetail;
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Forbidden
     */
    403: ApiProblemDetail;
};

export type ProvisionUserError = ProvisionUserErrors[keyof ProvisionUserErrors];

export type ProvisionUserResponses = {
    /**
     * User provisioned successfully
     */
    201: unknown;
};

export type ValidateUserData = {
    body: ValidateAuthUserIds;
    path?: never;
    query?: never;
    url: '/api/v1/user-provisions/validate';
};

export type ValidateUserErrors = {
    /**
     * One or more user IDs are invalid
     */
    400: ValidationProblemDetail;
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Forbidden
     */
    403: ApiProblemDetail;
};

export type ValidateUserError = ValidateUserErrors[keyof ValidateUserErrors];

export type ValidateUserResponses = {
    /**
     * All user IDs are valid
     */
    200: unknown;
};

export type GetUserAppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type GetUserAppointmentsErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetUserAppointmentsError = GetUserAppointmentsErrors[keyof GetUserAppointmentsErrors];

export type GetUserAppointmentsResponses = {
    /**
     * List of user appointments
     */
    200: Array<AppointmentResponse>;
};

export type GetUserAppointmentsResponse = GetUserAppointmentsResponses[keyof GetUserAppointmentsResponses];

export type CreateAppointmentData = {
    body: CreateAppointmentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type CreateAppointmentErrors = {
    /**
     * Invalid request
     */
    400: ValidationProblemDetail;
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Specialist not found
     */
    404: ApiProblemDetail;
    /**
     * Time slot already booked
     */
    409: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type CreateAppointmentError = CreateAppointmentErrors[keyof CreateAppointmentErrors];

export type CreateAppointmentResponses = {
    /**
     * Appointment created successfully
     */
    201: AppointmentResponse;
};

export type CreateAppointmentResponse = CreateAppointmentResponses[keyof CreateAppointmentResponses];

export type GetDocsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs';
};

export type GetDocsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDocsResponse = GetDocsResponses[keyof GetDocsResponses];

export type GetScalarJsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs/scalar.js';
};

export type GetScalarJsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetScalarJsResponse = GetScalarJsResponses[keyof GetScalarJsResponses];

export type GetUserMedicinesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user-medicines';
};

export type GetUserMedicinesErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * User not found
     */
    404: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetUserMedicinesError = GetUserMedicinesErrors[keyof GetUserMedicinesErrors];

export type GetUserMedicinesResponses = {
    /**
     * List of medicines
     */
    200: Array<UserMedicinesResponse>;
};

export type GetUserMedicinesResponse = GetUserMedicinesResponses[keyof GetUserMedicinesResponses];

export type GetAvailableSpecialistsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Specialist type
         */
        type?: SpecialistTypeEnum;
    };
    url: '/api/v1/specialists';
};

export type GetAvailableSpecialistsErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetAvailableSpecialistsError = GetAvailableSpecialistsErrors[keyof GetAvailableSpecialistsErrors];

export type GetAvailableSpecialistsResponses = {
    /**
     * List of specialists
     */
    200: Array<SpecialistResponse>;
};

export type GetAvailableSpecialistsResponse = GetAvailableSpecialistsResponses[keyof GetAvailableSpecialistsResponses];

export type GetSpecialistTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/specialists/types';
};

export type GetSpecialistTypesErrors = {
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetSpecialistTypesError = GetSpecialistTypesErrors[keyof GetSpecialistTypesErrors];

export type GetSpecialistTypesResponses = {
    /**
     * List of specialist types
     */
    200: Array<SpecialistTypeResponse>;
};

export type GetSpecialistTypesResponse = GetSpecialistTypesResponses[keyof GetSpecialistTypesResponses];

export type GetSpecialistBookingDataData = {
    body?: never;
    path: {
        /**
         * Specialist unique identifier
         */
        specialistId: string;
    };
    query: {
        /**
         * Start date (ISO-8601 format)
         */
        startDate: string;
        /**
         * End date (ISO-8601 format)
         */
        endDate: string;
    };
    url: '/api/v1/specialists/specialists/{specialistId}/booking-data';
};

export type GetSpecialistBookingDataErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Specialist not found
     */
    404: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetSpecialistBookingDataError = GetSpecialistBookingDataErrors[keyof GetSpecialistBookingDataErrors];

export type GetSpecialistBookingDataResponses = {
    /**
     * Specialist booking schedule
     */
    200: Array<DayScheduleResponse>;
};

export type GetSpecialistBookingDataResponse = GetSpecialistBookingDataResponses[keyof GetSpecialistBookingDataResponses];

export type GetUpcomingAppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/upcoming';
};

export type GetUpcomingAppointmentsErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetUpcomingAppointmentsError = GetUpcomingAppointmentsErrors[keyof GetUpcomingAppointmentsErrors];

export type GetUpcomingAppointmentsResponses = {
    /**
     * List of upcoming appointments
     */
    200: Array<AppointmentResponse>;
};

export type GetUpcomingAppointmentsResponse = GetUpcomingAppointmentsResponses[keyof GetUpcomingAppointmentsResponses];

export type GetPastAppointmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/history';
};

export type GetPastAppointmentsErrors = {
    /**
     * Unauthorized
     */
    401: ApiProblemDetail;
    /**
     * Internal server error
     */
    500: ApiProblemDetail;
};

export type GetPastAppointmentsError = GetPastAppointmentsErrors[keyof GetPastAppointmentsErrors];

export type GetPastAppointmentsResponses = {
    /**
     * List of past appointments
     */
    200: Array<AppointmentResponse>;
};

export type GetPastAppointmentsResponse = GetPastAppointmentsResponses[keyof GetPastAppointmentsResponses];

export type LinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator';
};

export type LinksResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: {
            [key: string]: Link;
        };
    };
};

export type LinksResponse = LinksResponses[keyof LinksResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actuator/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
