// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { cancelAppointment, createAppointment, getAppointmentById, getAvailableSpecialists, getDocs, getPastAppointments, getScalarJs, getSpecialistBookingData, getUpcomingAppointments, getUserAppointments, health, links, type Options, provisionUser, updateAppointment } from '../sdk.gen';
import type { CancelAppointmentData, CancelAppointmentError, CancelAppointmentResponse, CreateAppointmentData, CreateAppointmentError, CreateAppointmentResponse, GetAppointmentByIdData, GetAvailableSpecialistsData, GetDocsData, GetPastAppointmentsData, GetScalarJsData, GetSpecialistBookingDataData, GetUpcomingAppointmentsData, GetUserAppointmentsData, HealthData, LinksData, ProvisionUserData, ProvisionUserError, UpdateAppointmentData, UpdateAppointmentError, UpdateAppointmentResponse } from '../types.gen';

/**
 * Cancel appointment
 *
 * Cancels an existing appointment
 */
export const cancelAppointmentMutation = (options?: Partial<Options<CancelAppointmentData>>): UseMutationOptions<CancelAppointmentResponse, CancelAppointmentError, Options<CancelAppointmentData>> => {
    const mutationOptions: UseMutationOptions<CancelAppointmentResponse, CancelAppointmentError, Options<CancelAppointmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelAppointment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getAppointmentByIdQueryKey = (options: Options<GetAppointmentByIdData>) => createQueryKey('getAppointmentById', options);

/**
 * Get appointment by ID
 *
 * Returns a specific appointment by its unique identifier
 */
export const getAppointmentByIdOptions = (options: Options<GetAppointmentByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAppointmentById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAppointmentByIdQueryKey(options)
    });
};

/**
 * Update appointment
 *
 * Updates an existing appointment
 */
export const updateAppointmentMutation = (options?: Partial<Options<UpdateAppointmentData>>): UseMutationOptions<UpdateAppointmentResponse, UpdateAppointmentError, Options<UpdateAppointmentData>> => {
    const mutationOptions: UseMutationOptions<UpdateAppointmentResponse, UpdateAppointmentError, Options<UpdateAppointmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAppointment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Provision a user
 *
 * Creates a new Domain User. This action is triggered by the authentication service when a user is created.
 *
 */
export const provisionUserMutation = (options?: Partial<Options<ProvisionUserData>>): UseMutationOptions<unknown, ProvisionUserError, Options<ProvisionUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, ProvisionUserError, Options<ProvisionUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await provisionUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserAppointmentsQueryKey = (options?: Options<GetUserAppointmentsData>) => createQueryKey('getUserAppointments', options);

/**
 * Get user appointments
 *
 * Returns all appointments for the authenticated user
 */
export const getUserAppointmentsOptions = (options?: Options<GetUserAppointmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserAppointments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserAppointmentsQueryKey(options)
    });
};

/**
 * Create appointment
 *
 * Creates a new appointment with a specialist
 */
export const createAppointmentMutation = (options?: Partial<Options<CreateAppointmentData>>): UseMutationOptions<CreateAppointmentResponse, CreateAppointmentError, Options<CreateAppointmentData>> => {
    const mutationOptions: UseMutationOptions<CreateAppointmentResponse, CreateAppointmentError, Options<CreateAppointmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAppointment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDocsQueryKey = (options?: Options<GetDocsData>) => createQueryKey('getDocs', options);

export const getDocsOptions = (options?: Options<GetDocsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDocs({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDocsQueryKey(options)
    });
};

export const getScalarJsQueryKey = (options?: Options<GetScalarJsData>) => createQueryKey('getScalarJs', options);

export const getScalarJsOptions = (options?: Options<GetScalarJsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getScalarJs({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getScalarJsQueryKey(options)
    });
};

export const getAvailableSpecialistsQueryKey = (options?: Options<GetAvailableSpecialistsData>) => createQueryKey('getAvailableSpecialists', options);

/**
 * Get available specialists
 *
 * Returns list of all active specialists
 */
export const getAvailableSpecialistsOptions = (options?: Options<GetAvailableSpecialistsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAvailableSpecialists({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAvailableSpecialistsQueryKey(options)
    });
};

export const getSpecialistBookingDataQueryKey = (options: Options<GetSpecialistBookingDataData>) => createQueryKey('getSpecialistBookingData', options);

/**
 * Get specialist booking data
 *
 * Returns available time slots for a specialist within a date range
 */
export const getSpecialistBookingDataOptions = (options: Options<GetSpecialistBookingDataData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSpecialistBookingData({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSpecialistBookingDataQueryKey(options)
    });
};

export const getUpcomingAppointmentsQueryKey = (options?: Options<GetUpcomingAppointmentsData>) => createQueryKey('getUpcomingAppointments', options);

/**
 * Get upcoming appointments
 *
 * Returns upcoming appointments for the authenticated user
 */
export const getUpcomingAppointmentsOptions = (options?: Options<GetUpcomingAppointmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUpcomingAppointments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUpcomingAppointmentsQueryKey(options)
    });
};

export const getPastAppointmentsQueryKey = (options?: Options<GetPastAppointmentsData>) => createQueryKey('getPastAppointments', options);

/**
 * Get past appointments
 *
 * Returns past appointments for the authenticated user
 */
export const getPastAppointmentsOptions = (options?: Options<GetPastAppointmentsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPastAppointments({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPastAppointmentsQueryKey(options)
    });
};

export const linksQueryKey = (options?: Options<LinksData>) => createQueryKey('links', options);

/**
 * Actuator root web endpoint
 */
export const linksOptions = (options?: Options<LinksData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await links({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: linksQueryKey(options)
    });
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Actuator web endpoint 'health'
 */
export const healthOptions = (options?: Options<HealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await health({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: healthQueryKey(options)
    });
};
