/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignUpUserDataRouteImport } from './routes/auth/sign-up/user-data'
import { Route as AuthSignUpPaymentRouteImport } from './routes/auth/sign-up/payment'
import { Route as AuthCallbackSocialRouteImport } from './routes/auth/callback/social'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignUpRoute,
} as any)
const AuthSignUpUserDataRoute = AuthSignUpUserDataRouteImport.update({
  id: '/user-data',
  path: '/user-data',
  getParentRoute: () => AuthSignUpRoute,
} as any)
const AuthSignUpPaymentRoute = AuthSignUpPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AuthSignUpRoute,
} as any)
const AuthCallbackSocialRoute = AuthCallbackSocialRouteImport.update({
  id: '/callback/social',
  path: '/callback/social',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/callback/social': typeof AuthCallbackSocialRoute
  '/auth/sign-up/payment': typeof AuthSignUpPaymentRoute
  '/auth/sign-up/user-data': typeof AuthSignUpUserDataRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/callback/social': typeof AuthCallbackSocialRoute
  '/auth/sign-up/payment': typeof AuthSignUpPaymentRoute
  '/auth/sign-up/user-data': typeof AuthSignUpUserDataRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/callback/social': typeof AuthCallbackSocialRoute
  '/auth/sign-up/payment': typeof AuthSignUpPaymentRoute
  '/auth/sign-up/user-data': typeof AuthSignUpUserDataRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/auth/sign-up'
    | '/admin/'
    | '/auth/'
    | '/api/auth/$'
    | '/auth/callback/social'
    | '/auth/sign-up/payment'
    | '/auth/sign-up/user-data'
    | '/auth/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/admin'
    | '/auth'
    | '/api/auth/$'
    | '/auth/callback/social'
    | '/auth/sign-up/payment'
    | '/auth/sign-up/user-data'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/auth/sign-up'
    | '/admin/'
    | '/auth/'
    | '/api/auth/$'
    | '/auth/callback/social'
    | '/auth/sign-up/payment'
    | '/auth/sign-up/user-data'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthSignUpRoute
    }
    '/auth/sign-up/user-data': {
      id: '/auth/sign-up/user-data'
      path: '/user-data'
      fullPath: '/auth/sign-up/user-data'
      preLoaderRoute: typeof AuthSignUpUserDataRouteImport
      parentRoute: typeof AuthSignUpRoute
    }
    '/auth/sign-up/payment': {
      id: '/auth/sign-up/payment'
      path: '/payment'
      fullPath: '/auth/sign-up/payment'
      preLoaderRoute: typeof AuthSignUpPaymentRouteImport
      parentRoute: typeof AuthSignUpRoute
    }
    '/auth/callback/social': {
      id: '/auth/callback/social'
      path: '/callback/social'
      fullPath: '/auth/callback/social'
      preLoaderRoute: typeof AuthCallbackSocialRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthSignUpRouteChildren {
  AuthSignUpPaymentRoute: typeof AuthSignUpPaymentRoute
  AuthSignUpUserDataRoute: typeof AuthSignUpUserDataRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpPaymentRoute: AuthSignUpPaymentRoute,
  AuthSignUpUserDataRoute: AuthSignUpUserDataRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

interface AuthRouteChildren {
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCallbackSocialRoute: typeof AuthCallbackSocialRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthCallbackSocialRoute: AuthCallbackSocialRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
